version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Mayuresh@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  assetapi:
    build: .
    container_name: assetapi
    ports:
      - "5114:8080"   # HTTP
      - "7242:8081"   # HTTPS
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Mayuresh@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - DB_USER=sa
      - DB_PASSWORD=Mayuresh@123
    depends_on:
      - sqlserver
      - rabbitmq
    volumes:
      - ./https:/https:ro

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backgroundcalculator:
    build:
      context: .
      dockerfile: BackgroundCalculatorService/Dockerfile
    container_name: backgroundcalculator
    depends_on:
      - rabbitmq
      - assetapi
      - sqlserver
    environment:
      - ASSETAPI_URL=http://assetapi:8080/api/AssetHierarchy/SendFromWorker
      - RABBITMQ_HOST=rabbitmq
      - DB_USER=sa
      - DB_PASSWORD=Mayuresh@123
    restart: always

volumes:
  sql_data: 